### ISSUE TITLE
qwiic level translator?

### ISSUE THREAD

**Issue by egregori3** [sparkfun/PCA9306_Level_Translator_Breakout#6]
It would be great to have a board like this with qwiic headers on both sides.
I need to connect a 1.8v I2C master to some qwiic sensors and the qwiic cables are so convenient.

**Comment by nseidle** [comment]
A fine idea. Going on the to do list!

**Comment by nseidle** [comment]
The Qwiic 1.8V adapter is available [here](https://www.sparkfun.com/products/19017) if you need it. Thanks for the recommendation!
